version: "3.5"

services:
  web-phpinfo:
    image: nginx:1.17-alpine
    container_name: nginx-phpinfo-8.2.18
    restart: unless-stopped
    ports:
      - "${PHPINFO_PORT}:80"
#      - "4482:433"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ../app-phpinfo/phpinfo:/usr/share/nginx/html/
    networks:
      - nginx
    depends_on:
      - fpm-phpinfo
    links:
      - fpm-phpinfo

  fpm-phpinfo:
    # NOTE: change it with the preferred PHP version
    #    build:
    #      context: "${PWD}"
    #      dockerfile: "${PWD}/8.0-fpm/Dockerfile"
    image: php-fpm-8.2:8.2.18
    container_name: fpm-phpinfo-8.2.18
    restart: unless-stopped
    working_dir: "/usr/share/nginx/html"
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9082"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    expose:
      - "9082"
    volumes:
      - ../app-phpinfo/phpinfo:/usr/share/nginx/html/
    networks:
      - mysql8
      - nginx

networks:
  nginx:
  mysql8:
    name: mysql8