version: "3.3"

services:
  web-phpinfo:
    image: nginx:1.17-alpine
    container_name: nginx-phpinfo-7.4.33
    restart: unless-stopped
    ports:
      - "${PHPINFO_PORT}:80"
#      - "4474:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ../app-phpinfo/phpinfo:/usr/share/nginx/html/
    depends_on:
      - fpm-phpinfo
    links:
      - fpm-phpinfo

  fpm-phpinfo:
    # NOTE: change it with the preferred PHP version
#    build:
#      context: "${PWD}"
#      dockerfile: "${PWD}/7.4-fpm/Dockerfile"
    image: php-fpm-7.4:7.4.33
    container_name: fpm-phpinfo-7.4.33
    restart: unless-stopped
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_FPM_LISTEN=9074"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    expose:
      - "7433"
    volumes:
      - ../app-phpinfo/phpinfo:/usr/share/nginx/html/
